name: "Build&Deploy spawner-base images"

on:
  # Trigger the workflow on push or pull request
  # but only for the main branch
  # or on tag of type v*.*.*
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - dev
  release:
    types: [released]
jobs:
  spawner-base-melodic:
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@main
    with:
      docker_file: docker/melodic/Dockerfile
      docker_image: devops/spawner-base-melodic
      github_ref: ${{ github.ref }}
      public: true
      public_image: ce/spawner-base-melodic
      target: spawner
    secrets:
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}

  spawner-base-noetic:
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@main
    with:
      docker_file: docker/noetic/Dockerfile
      docker_image: devops/spawner-base-noetic
      github_ref: ${{ github.ref }}
      public: true
      public_image: ce/spawner-base-noetic
      target: spawner
    secrets:
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}

  spawner-ign-melodic:
    needs: [ "spawner-base-melodic" ]
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@main
    with:
      docker_file: docker/melodic/Dockerfile
      docker_image: devops/spawner-ign-melodic
      github_ref: ${{ github.ref }}
      public: true
      public_image: ce/spawner-ign-melodic
      target: spawner-ign
    secrets:
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}

  spawner-ign-noetic:
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@main
    needs: [ "spawner-base-noetic" ]
    with:
      docker_file: docker/noetic/Dockerfile
      docker_image: devops/spawner-ign-noetic
      github_ref: ${{ github.ref }}
      public: true
      public_image: ce/spawner-ign-noetic
      target: spawner-ign
    secrets:
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
