name: "Build&Deploy spawner-base images"

on:
  # Trigger the workflow on push or pull request
  # but only for the main branch
  # or on tag of type v*.*.*
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - dev
  release:
    types: [released]
jobs:
  spawner-base-melodic:
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@main
    with:
      docker_file: docker/melodic/Dockerfile
      docker_image: ce/spawner-base-melodic
      github_ref: ${{ github.ref }}
    secrets:
      registry_user: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}

  spawner-base-noetic:
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@main
    with:
      docker_file: docker/noetic/Dockerfile
      docker_image: ce/spawner-base-noetic
      github_ref: ${{ github.ref }}
      target: spawner
    secrets:
      registry_user: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}

  spawner-ign-melodic:
    needs: [ "spawner-base-melodic" ]
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@main
    with:
      docker_file: docker/melodic/Dockerfile
      docker_image: ce/spawner-ign-melodic
      github_ref: ${{ github.ref }}
      target: spawner-ign
    secrets:
      registry_user: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}

  spawner-ign-noetic:
    uses: MOV-AI/.github/.github/workflows/docker-workflow.yml@main
    needs: [ "spawner-base-noetic" ]
    with:
      docker_file: docker/noetic/Dockerfile
      docker_image: ce/spawner-ign-noetic
      github_ref: ${{ github.ref }}
    secrets:
      registry_user: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}
